version: "3"
services:

  speedtest:
    container_name: monitoring-speedtest
    restart: unless-stopped
    image: robinmanuelthiel/speedtest:latest
    networks:
      - monitoring
    environment:
      LOOP: "true"
      LOOP_DELAY: 7200
      DB_SAVE: "true"
      DB_HOST: http://influxdb-speedtest:8086
      DB_NAME: speedtest
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Berlin
    privileged: true # Needed for 'sleep' in the loop
    depends_on:
      influxdb:
        condition: service_started

  influxdb:
    container_name: monitoring-speedtest-influxdb
    build:
      context: .
      dockerfile: Dockerfile-influx
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    expose:
      - 8083
      - 8086
    ports:
      - "8087:8086"
    hostname: influxdb-speedtest
    networks:
      - monitoring
    environment:
      INFLUXDB_DB: speedtest
      INFLUXDB_ADMIN_USER: ${DB_USERNAME}
      INFLUXDB_ADMIN_PASSWORD:  ${DB_PASSWORD}
      TZ: Europe/Berlin
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8086 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  influxdb:


networks:
  monitoring:
    external: true

