version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: bricksoft/speedtest
        ports:
            - 8765:80
        volumes:
            - ./config:/config
        environment:
            - TZ=
            - OOKLA_EULA_GDPR=true
        restart: unless-stopped
