version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: bricksoft/speedtest
        ports:
            - 8765:80
        volumes:
            - ./config:/config
        environment:
            - TZ=
            - OOKLA_EULA_GDPR=true
        restart: unless-stopped
        healthcheck:
          test: curl --fail http://localhost || exit 1
          interval: 60s
          retries: 5
          start_period: 20s
          timeout: 10s
